Repository Project-Skill-Tree/Skill-Tree-API, pull requests merged in 2022-04, with the labels that each got.

#13 Yet another patch for running with heroku
  Procfile
Labels: enhancement

#11 Create node.js.yml
  .github/workflows/node.js.yml
Labels: enhancement

#15 fixed Procfile to work with heroku
  Procfile
Labels: enhancement

#17 Feature list
  FEATURES.md
Labels: documentation

#18 Update workflow to only support 16.x
  .github/workflows/node.js.yml
Labels: enhancement

#16 Added error handling for mongoose.connect
  src/loaders/mongooseLoader.js
Labels: enhancement

#20 Error handling for the /skills POST request
  src/api/controllers/skill.controller.js
  src/models/skill.model.js
Labels: enhancement

#24 Users
  .env.example
  package-lock.json
  package.json
  src/api/controllers/user.controller.js
  src/api/routes/index.js
  src/api/routes/v1/user.routes.js
  src/index.js
  src/models/user.model.js
  swagger-output.json
  swagger.js
Labels: enhancement

#25 Update GitHub workflow
  .github/workflows/node.js.yml
  package-lock.json
  package.json
  src/api/controllers/skill.controller.js
  src/api/controllers/user.controller.js
  src/api/routes/index.js
  src/api/routes/v1/skill.routes.js
  src/api/routes/v1/user.routes.js
  src/index.js
  src/loaders/expressLoader.js
  src/loaders/mongooseLoader.js
  src/models/skill.model.js
  src/models/user.model.js
  swagger.js
Labels: documentation, enhancement

#26 Validate api key
  src/api/controllers/skill.controller.js
  src/models/skill.model.js
Labels: enhancement
